Fix find index (i.e. don't use -1)
DHI/mikeio pull request #541
Opened 2023-01-24 13:22 UTC by ecomodeller

#539

2023-01-24 16:47 UTC, ecomodeller commented
@jsmariegaard I changed the signature for `_find_element_2d(self, x: float, y: float) -> int:` to make it easier to reason about.

TL;DR we have not properly tested the behaviour for points outside the domain😳

2023-01-25 08:43 UTC, jsmariegaard commented
I see that you did a major revision of _find_element_2d(). It looked the way it did, after quite a lot of optimization work trying to make it as fast as possible for many points on large meshes. So maybe you could do a few benchmark tests? Or maybe we should do a c-implementation of this anyway...

2023-01-25 09:02 UTC, ecomodeller commented
Results from first "benchmark"
![image](https://user-images.githubusercontent.com/614215/214521585-aa4fcb58-d5f1-43d1-9a91-2c1f41975010.png)

2023-01-25 09:18 UTC, jsmariegaard commented
Could you do the same for the main branch?

2023-01-25 12:18 UTC, ecomodeller commented
## Code qualities:
1. Correct
2. Predictable
3. Fast
![image](https://user-images.githubusercontent.com/614215/214560953-e98e1213-10fe-4614-8397-a28b29e44101.png)

2023-01-25 13:25 UTC, ecomodeller commented
`_find_nearest_2d_elements` is pretty fast thanks to https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.query.html
![image](https://user-images.githubusercontent.com/614215/214574276-f30f8305-5a48-4ec4-be3c-316834447a85.png)

And you know what Knuth thinks about premature optimization...

2023-01-30 13:32 UTC, ecomodeller commented
@jsmariegaard Can we merge this?

2023-01-30 15:24 UTC, jsmariegaard commented
I'll have a look today

2023-01-30 16:28 UTC, jsmariegaard requested changes
Lots of good stuff. But generally, I would prefer if find_index returns an np.array of int. If I give you an array of 100 positions (stations), I would like to have an array of indices back (similar to `contains()` ), not an unordered set. If I use the isel method I would get a DataArray/Dataset back for which a geometry would have been constructed and in that case the ordering should dissapear (like the non-uniqueness of found points). Let's talk tomorrow.

2023-01-30 16:28 UTC, jsmariegaard commented on mikeio/spatial/FM_geometry.py
> +                    raise OutsideModelDomainError(x=coords[k, 0], y=coords[k, 1])
add k as info to error message. And even better - loop over all coords first and find out which are outside and provide user a list of all points outside so he/she does not need to call this method many times just to find out that the next point is also outside

2023-01-30 16:28 UTC, jsmariegaard commented on mikeio/spatial/FM_geometry.py
> +        """Find a *set* of element indicies for a number of points or within an area
Maybe state that this means that the returned collection is unordered and unique? (most people would know what a set is, but we also have many in-experienced python users).

2023-01-30 16:28 UTC, jsmariegaard commented on mikeio/spatial/grid_geometry.py
> +        ii = (-999999999) * np.ones_like(x, dtype=int)  # TODO -999999999 ?
remove TODO

2023-02-14 06:45 UTC, jsmariegaard requested changes
Still not happy about returning a set when you have a list of stations that you would like to find the corresponding indicies for - how do you recommend the user should get this now? 

I can see the problem about that find index takes both an area and a coords argument and that it is difficult to return the same datastructure in both cases... I would prefer to get an array with the same order as the input if possible and otherwise simply ordered by id. 

If you want to keep the current implementation (and I guess you will), then you should be consistent: right now only 3 out of the 6 find_index methods return a set:

![image](https://user-images.githubusercontent.com/34088801/218659772-ca5298f9-f68a-4e99-97c3-e4283cd391a9.png)

2023-02-14 15:34 UTC, ecomodeller commented
> Still not happy about returning a set when you have a list of stations that you would like to find the corresponding indicies for - how do you recommend the user should get this now?
> 
> I can see the problem about that find index takes both an area and a coords argument and that it is difficult to return the same datastructure in both cases... I would prefer to get an array with the same order as the input if possible and otherwise simply ordered by id.
> 
> If you want to keep the current implementation (and I guess you will), then you should be consistent: right now only 3 out of the 6 find_index methods return a set:
> 
> ![image](https://user-images.githubusercontent.com/34088801/218659772-ca5298f9-f68a-4e99-97c3-e4283cd391a9.png)

We need two methods
* one method to return a indices of a subset which we can construct a meaningful geometry from, this will only work for FMGeometries and potentially for a connected subset of a gridded geometry (we can not support disconnected grid geometries)
* another method to return indices for every point in a list of points

And these methods have to be named in a meaningful way.

2023-02-14 16:30 UTC, ecomodeller commented
> > Still not happy about returning a set when you have a list of stations that you would like to find the corresponding indicies for - how do you recommend the user should get this now?
> > I can see the problem about that find index takes both an area and a coords argument and that it is difficult to return the same datastructure in both cases... I would prefer to get an array with the same order as the input if possible and otherwise simply ordered by id.
> > If you want to keep the current implementation (and I guess you will), then you should be consistent: right now only 3 out of the 6 find_index methods return a set:
> > ![image](https://user-images.githubusercontent.com/34088801/218659772-ca5298f9-f68a-4e99-97c3-e4283cd391a9.png)

`_GeometryFMLayered.find_index` and `GeometryFMVerticalProfile.find_index` uses [`np.intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html) which returns "..the sorted, unique values...". Should we return this instead of a `set[int]` for all methods? 

My point is that unique values is not the same as a list of indices for each point, since many of the input locations will likely belong to the same element.

2023-02-14 16:42 UTC, ecomodeller commented
And while looking at spatial subselection in 3d files, there seems to be two methods with identical purpose, one used by the `Dfsu.read` and the other used by `Dataset.sel`
![image](https://user-images.githubusercontent.com/614215/218800697-60666519-8d82-4054-aec3-72a34151359e.png)

`_parse_geometry_sel` delegates to `find_index` but not with all arguments 🤔

2023-03-02 12:58 UTC, merged